# Generated by Django 5.1.2 on 2024-11-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_curriculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacao',
            name='dados_pessoais',
        ),
        migrations.RemoveField(
            model_name='educacao',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='educacao',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='educacao',
            name='grau',
        ),
        migrations.AddField(
            model_name='educacao',
            name='curso',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educacao',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educacao',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Em andamento', 'Em andamento'), ('Trancado', 'Trancado')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educacao',
            name='instituicao',
            field=models.CharField(max_length=255),
        ),
    ]
